src/Arto/GreenBundle/Form/UserType.php
<?php

namespace Arto\GreenBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class UserType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('firstname', null, array('required' => true))
            ->add('lastname', null, array('required' => true))
            ->add('majority', null, array('required' => true))
            ->add('address', null, array('required' => true))
            ->add('city', null, array('required' => true))
            ->add('postcode', null, array('required' => true))
            ->add('company', null, array('required' => true))
            ->add('activity', null, array('required' => true))
            ->add('siret', null, array('required' => true))
            ->add('email', null, array('required' => true))
            ->add('password', null, array('required' => true))    
            ->add('tel', null, array('required' => true))
            ->add('capital', null, array('required' => true))
            ->add('optin', null, array('required' => true))
            ->add('accept1', null, array('required' => true))
            ->add('accept2', null, array('required' => true))
        ;
    }

    public function getName()
    {
        return 'usertype';
    }
}

src/Arto/GreenBundle/Resources/views/Page/page.html.twig
{% set section = "home" %}

{% extends '::base.html.twig' %}

{% block body %}

<section class="main white service-page">
    <ul class="page-nav">
        <li><a href="#" onclick="history.back(-1);return false;" style="color: #cc0066;"><i class="icon-angle-left"></i> Retour</a></li>
        <li><a href="#" onclick="$('nav .home').click();return false;" style="color: #008ebf;"><i class="icon-th-list"></i> Sommaire</a></li>
    </ul>
    <h2><i class="icon-quote-left pull-left icon-muted"></i> {{ page.name }}</h2>
    <div class="description">
        <div class="wysiwyg">
            {{ page.description|raw }}
        </div>
    </div>
</section>

{% endblock %}