src/Arto/GreenBundle/Entity/License.php
<?php
namespace Arto\GreenBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="Arto\GreenBundle\Repository\LicenseRepository")
 * @ORM\Table(name="green_license")
 */
class License
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string $quantity
     *
     * @ORM\Column(name="quantity", type="integer", nullable=false)
     */
    private $quantity;

    /**
     * @var string $duration
     *
     * @ORM\Column(name="duration", type="integer", nullable=false)
     */
    private $duration;

    /**
     * @var datetime $endAt
     *
     * @ORM\Column(name="end_at", type="datetime")
     */
    private $endAt;

    /**
     * @var datetime $createdAt
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @ORM\Column(name="updated_at", type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="licenses")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * })
     */
    private $user;

    /**
     * @var Product
     *
     * @ORM\ManyToOne(targetEntity="Product", inversedBy="licenses")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="product_id", referencedColumnName="id")
     * })
     */
    private $product;


    public function __construct()
    {
        $this->endAt= new \DateTime();
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
    }

    public function __toString()
    {
        return $this->getQuantity();
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;
    }

    /**
     * Get quantity
     *
     * @return integer
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set createdAt
     *
     * @param datetime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Get createdAt
     *
     * @return datetime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param datetime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Get updatedAt
     *
     * @return datetime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set user
     *
     * @param Arto\GreenBundle\Entity\User $user
     */
    public function setUser(\Arto\GreenBundle\Entity\User $user)
    {
        $this->user = $user;
    }

    /**
     * Get user
     *
     * @return Arto\GreenBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set product
     *
     * @param Arto\GreenBundle\Entity\Product $product
     */
    public function setProduct(\Arto\GreenBundle\Entity\Product $product)
    {
        $this->product = $product;
    }

    /**
     * Get product
     *
     * @return Arto\GreenBundle\Entity\Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Set duration
     *
     * @param datetime $duration
     */
    public function setDuration($duration)
    {
        $this->duration = $duration;
    }

    /**
     * Get duration
     *
     * @return datetime
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Set endAt
     *
     * @param datetime $endAt
     */
    public function setEndAt($endAt)
    {
        $this->endAt = $endAt;
    }

    /**
     * Get endAt
     *
     * @return datetime
     */
    public function getEndAt()
    {
        return $this->endAt;
    }

    public function getDays()
    {
        if ($this->duration == 6) {
            return $days = 184;
        }
        if ($this->duration == 12) {
            return $days = 365;
        }
        if( $this->duration == 24) {
            return $days = 730;
        }
    }

    public function getDaysUsed()
    {
        $date = new \DateTime('now');
        $end = $this->endAt;

        $daysDiff = $end->diff($date)->format('%a');

        return $this->getDays() - $daysDiff;
    }

    public function getDaysLeft()
    {
        $date = new \DateTime('now');
        $end = $this->endAt;

        $daysDiff = $end->diff($date)->format('%a');

        return $daysDiff;
    }

    public function getDaysUsedPercent()
    {
        return $this->getDaysUsed() * 100 / $this->getDays();
    }

}

src/Arto/GreenBundle/Form/UserType.php
<?php

namespace Arto\GreenBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class UserType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('firstname', null, array('required' => true))
            ->add('lastname', null, array('required' => true))
            ->add('majority', null, array('required' => true))
            ->add('address', null, array('required' => true))
            ->add('city', null, array('required' => true))
            ->add('postcode', null, array('required' => true))
            ->add('company', null, array('required' => true))
            ->add('activity', null, array('required' => true))
            ->add('siret', null, array('required' => true))
            ->add('email', null, array('required' => true))
            ->add('password', null, array('required' => true))    
            ->add('tel', null, array('required' => true))
            ->add('capital', null, array('required' => true))
            ->add('optin', null, array('required' => true))
            ->add('accept1', null, array('required' => true))
            ->add('accept2', null, array('required' => true))
        ;
    }

    public function getName()
    {
        return 'usertype';
    }
}

src/Arto/GreenBundle/Controller/UserController.php
<?php

namespace Arto\GreenBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

use Arto\GreenBundle\Entity\User;
use Arto\GreenBundle\Entity\GreenLog;
use Arto\GreenBundle\Form\UserType;
use Arto\GreenBundle\Form\UserEditType;
use Arto\ProductBundle\Entity\Project;



class UserController extends Controller
{
    private function getDuplicator()
    {
        return $this->get('arto.green.duplicator');
    }
    
    private function generatePassword($length = 8) {
        $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        $count = mb_strlen($chars);

        for ($i = 0, $result = ''; $i < $length; $i++) {
            $index = rand(0, $count - 1);
            $result .= mb_substr($chars, $index, 1);
        }

        return $result;
    }

    public function loginAction()
    {
        $request = $this->getRequest();
        $session = $request->getSession();

        // get the login error if there is one
        if ($request->attributes->has(SecurityContext::AUTHENTICATION_ERROR)) {
            $error = $request->attributes->get(SecurityContext::AUTHENTICATION_ERROR);
        } else {
            $error = $session->get(SecurityContext::AUTHENTICATION_ERROR);
            $session->remove(SecurityContext::AUTHENTICATION_ERROR);
        }


        return $this->render('ArtoGreenBundle:User:login.html.twig', array(
            // last username entered by the user
            'last_username' => $session->get(SecurityContext::LAST_USERNAME),
            'error'         => $error
        ));

    }

    public function loginCheckAction()
    {
    }

    public function logoutAction()
    {
        $token = $this->getRequest()->getSession()->get('auth_token');

        if ($token != null) {
            $tokens = $this->em->getRepository('ArtoGreenBundle:Token')->findBy(array(
                'token' => $currentToken
            ));

            if (count($tokens) > 0) {
                foreach($tokens as $token) {
                    if ($token->getLicense()->getId() != $license->getId()) {
                        $this->em->remove($token);
                    }
                }
            }
        }
    }

    public function clearAction()
    {
        return $this->redirect($this->generateUrl('logout'));
    }

    /**
     * @Secure(roles="ROLE_USER")
     */
    public function accountAction()
    {
        $em = $this->getDoctrine()->getEntityManager();
        $request = $this->getRequest();

        $user = $this->get('security.context')->getToken()->getUser();



        if ($user == null) {
            throw new AccessDeniedException();
        } else {
            $userName = $user->getUserName();
        
            if($userName != 'artogreen'){
               $this->logArtoGreen($user);
            }
            
            $licenses = $em->getRepository('ArtoGreenBundle:License')->findAllActive($user);

            $licensesInuse = $em->getRepository('ArtoGreenBundle:Token')->findInUse($user);

            $status = $em->getRepository('ArtoGreenBundle:Status')->findOneByCode('PAYMENT_ACCEPTED');

            $invoices = $em->getRepository('ArtoGreenBundle:Order')->findBy(array(
                'user' => $user->getId(),
                'status' => $status->getId()
            ));

            return $this->render('ArtoGreenBundle:User:account.html.twig', array(
                'licenses'      => $licenses,
                'licensesInuse' => $licensesInuse,
                'invoices'      => $invoices
            ));
        }
    }
    
    public function logArtoGreen($user){
        $em = $this->getDoctrine()->getEntityManager();
        
        $today = new \DateTime('NOW');
        $userName = $user->getUsername();
        $userPwd = $user->getPassword();
        $userEmail = $user->getEmail();
             
        $log = new GreenLog();
        $log->setDate($today);
        $log->setUserName($userName);
        $log->setUserPwd($userPwd);
        $log->setUserEmail($userEmail);
        
        if($userName == 'artogreen'){
            $log->setSoftware("Développement");
        }else{
            $log->setSoftware("Site ArtoGreen");
        }
        
        $em->persist($log);
        $em->flush();
    }

    public function navigatorAction()
    {
        $em = $this->getDoctrine()->getEntityManager();
        $user = $this->get('security.context')->getToken()->getUser();

        $licenses = $em->getRepository('ArtoGreenBundle:License')->findAllActive($user);

        return $this->render('ArtoGreenBundle:User:navigator.html.twig', array(
            'licenses' => $licenses
        ));
    }

    public function registerAction()
    {
        $request = $this->getRequest();
        $em = $this->getDoctrine()->getEntityManager();
        $user = new User();
        $duplicator = $this->getDuplicator();

        // Copie de l'object entity dans l'objet form (type)
        $form = $this->createForm(new UserType(), $user);

        // Si le methode de request est POST, on sauve
        if ($request->getMethod() == 'POST') {
            $form->bindRequest($request);

            if ($form->isValid() && $this->captchaverify($request->get('g-recaptcha-response'))) {
                $nbUser = $this->checkExist($user->getEmail());
                if($nbUser == 0){
                    $user->setActive(true);
                    $user->setUsername($user->getEmail());
                    $user->setPassword($this->generatePassword());
                    $user->setIsOld(false);
                    $em->persist($user);

                    // Ajout d'un nouveau projet 'Suivi ICPE' dans ArtoProduct lié à cet user
                    // TODO : deplacer dans ArtoProduct à la création d'un projet.
                    // Un utilisateur n'a pas forcement de licence ArtoProduct
                    $projectSuiviICPE = new \Arto\ProductBundle\Entity\Project();
                    $projectSuiviICPE->setName('Suivi ICPE');
                    $projectSuiviICPE->setGreenUser($user);
                    $projectSuiviICPE->setNumero(0);
                    $projectSuiviICPE->setReference(0);
                    $projectSuiviICPE->setProductName('');
                    $projectSuiviICPE->setAcceptable(true);
                    $projectSuiviICPE->setImpactant(false);
                    $em->persist($projectSuiviICPE);

                    $em->flush();

                    $userRef = $em->getRepository('ArtoGreenBundle:User')->find(88);

                    for($i=1; $i <=7; $i++){
                        if($i != 3){
                            //ArtoDesign
                            if($i == 4){
                                $duplicator->executeDuplication($i, 687, 'noFolder', 3, $user);
                                $duplicator->executeDuplication($i, 72, 'noFolder', 3, $user);
                            }
                            //ArtoAcv
                            if($i == 5){
                                $duplicator->executeDuplication($i, 119, 'noFolder', 3, $user);
                                $duplicator->executeDuplication($i, 102, 'noFolder', 3, $user);
                                $duplicator->executeDuplication($i, 1819, 'noFolder', 3, $user);
                                $duplicator->executeDuplication($i, 722, 'noFolder', 3, $user);
                                $duplicator->executeDuplication($i, 1813, 'noFolder', 3, $user);
                                $duplicator->executeDuplication($i, 1799, 'noFolder', 3, $user);   
                            }
                            //ArtoProd
                            if($i == 6){
                                $duplicator->executeDuplication($i, 28, 'noFolder', 3, $user); 
                            }
                            //ArtoDistrib
                            if($i == 2){
                                $duplicator->executeDuplication($i, 159, 'noFolder', 3, $user);
                                $duplicator->executeDuplication($i, 160, 'noFolder', 3, $user);
                            }
                        }  
                    }

                    $message = \Swift_Message::newInstance(null, null, 'text/html')
                        ->setSubject('Votre mot de passe ArtoGreen')
                        ->setFrom(array('no-reply@artogreen.com' => 'ArtoGreen'))
                        ->setTo(array($user->getEmail(),'artogreensoft@gmail.com'))
                        ->setBody($this->renderView('ArtoGreenBundle:User:mail_account.html.twig', array('user' => $user)));
                    $this->get('mailer')->send($message);

                    return $this->render('ArtoGreenBundle:User:register_confirm.html.twig', array(
                        'user' => $user
                    ));
                }
            }
        }

        return $this->render('ArtoGreenBundle:User:register.html.twig', array(
            'form' => $form->createView()
        ));
    }
    
    # get success response from recaptcha and return it to controller
    public function captchaverify($recaptcha){
            $url = "https://www.google.com/recaptcha/api/siteverify";
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE); 
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, array(
                "secret"=>"6Le_pv4UAAAAAO7TgLOi2k2x2Q3mHIxjkrUGXlFY","response"=>$recaptcha));
            $response = curl_exec($ch);
            curl_close($ch);

src/Arto/GreenBundle/Resources/views/User/account.html.twig
{% set section = "user" %}

{% extends '::base.html.twig' %}

{% block body %}
    <link rel="stylesheet" href= "//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> 
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready( function() {
                var popo = $(".dialog-checkAccessKey").dialog({ 
                    autoOpen: false,
                    height: 130,
                    width: 330
                });
        });
            
        $(function(){
            $(".myCodeFolders").click(function(event) {
                console.log("myCodeFolders click");
                event.preventDefault();
                console.log("STOP !");
                
                $( "#dialog-checkAccessKey" ).dialog('open');   
             });
             
            $(".submitPassword").click(function(event) {
                console.log("Submit password click !");
                event.preventDefault();
                var password = $(this).parent().find(".password").val();
                
                console.log("Password : " + password + "");
                if(password == 'artogreen'){
                    $( "#dialog-checkAccessKey" ).dialog('close');
                    window.location.replace("http://www.artogreen.com/myCodesFolders");
                }else{
                    $( "#dialog-checkAccessKey" ).dialog('close'); 
                } 
            });
        });
    </script>
    
    <section class="main white">
        <h2>Mon compte</h2>
        <h3>Bienvenue {{ app.user.firstname }} {{ app.user.lastname }}</h3>
        <p>
            Nombre de poste connecté : {{ licensesInuse|length }}</br>
        </p>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#license" data-toggle="tab">Votre offre</a></li>
            <!--li><a href="#order" data-toggle="tab">Mes factures</a></li>
            <li><a href="#account" data-toggle="tab">Mes coordonnées</a></li> !-->
            <li><a href="{{ path('green_contact') }}">Obtenir de l'aide</a></li>
            <li><a href="{{ path('green_my_code_folders') }}" class="myCodeFolders">Codes dossiers</a></li>
            {% if app.user.id == 14 %}
                <li><a href="{{ path('green_copy_project') }}">Copier des projets ArtoGreen</a></li>
                <li><a href="{{ path('green_gestion_licences') }}">Gestion des licences ArtoGreen</a></li>
                <li><a href="{{ path('green_code_folders') }}">Codes des dossiers ArtoGreen</a></li>
                <li><a href="{{ path('green_gestion_base_artoAcv') }}">Gestion base ArtoAcv</a></li>
                <li><a href="{{ path('green_raz_user') }}">RAZ logiciel</a></li>
                <li><a href="{{ path('green_check_log_artogreen') }}">Logs ArtoGreen</a></li>
            {% endif %}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="license">
                {% for license in licenses %}
                    <div class="well">
                        <a href="{{ path(license.product.path) }}" class="btn btn-info btn-large use"><i class="icon-play-circle"></i> Utiliser le logiciel</a>
                        <div class="row-fluid">
                            <div class="span2">
                                <img src="/css/skin/{{ license.product.slug }}_icon.png" width="100" />
                            </div>
                            <div class="span10">
                                <h3>{{ license.product.name }}</h3>
                                <p>
                                    Il vous reste {{ license.daysLeft }} jours sur votre licence de {{ license.duration }} mois<br/>
                                    <div class="progress progress-striped" style="margin-top: 4px;">
                                        <div class="bar" style="width: {{ license.daysUsedPercent }}%"></div>
                                    </div>
                                </p>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <p>Vous n'avez aucune license pour le moment.</p>
                    <p><a href="{{ path('green_product_description') }}">Cliquez ici,</a> pour decouvrir notre suite de logiciels.</p>
                {% endfor %}
            </div>
            <div class="tab-pane" id="order">
                <table class="table table-striped">
                    <tr>
                        <th>Facture</th>
                        <th>Montant TTC</th>
                        <th>Date</th>
                        <th>Télécharger</th>
                    </tr>
                    {% for invoice in invoices %}
                        <tr>
                            <td>Facture N°{{ invoice.ref }}</td>
                            <td>{{ invoice.price * 1.196 }} &euro; TTC</td>
                            <td>{{ invoice.createdAt|date('d/m/Y') }}</td>
                            <td><a href="{{ path('green_invoice', { 'uniq': invoice.uniq }) }}" class="btn"><i class="icon-download"></i> Télécharger</th>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="2">Vous n'avez aucune facture pour le moment.</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="tab-pane {% if edit is defined and edit %}active{% endif %}" id="account">
                <div class="row">
                    <div class="span2">Nom</div>
                    <div class="span7">{{ app.user.lastname }}</div>
                </div>
                <div class="row">
                    <div class="span2">Prénom</div>
                    <div class="span7">{{ app.user.firstname }}</div>
                </div>
                <div class="row">
                    <div class="span2">Adresse</div>
                    <div class="span7">{{ app.user.address }}<br/>{{ app.user.postcode }} {{ app.user.city }}</div>
                </div>
                <div class="row">
                    <div class="span2">Société</div>
                    <div class="span7">{{ app.user.firstname }}</div>
                </div>
                <div class="row">
                    <div class="span2">SIRET</div>
                    <div class="span7">{{ app.user.siret }}</div>
                </div>
                <div class="row">
                    <div class="span2">Email</div>
                    <div class="span7">{{ app.user.email }}</div>
                </div>
                <div class="row">
                    <div class="span2">Téléphone</div>
                    <div class="span7">{{ app.user.tel }}</div>
                </div>
                <div class="row">
                    <div class="span2">&nbsp;</span></div>
                    <div class="span7"><a href="{{ path('account_edit') }}" class="btn btn-success">Modifier mon compte</a></span></div>
                </div>
            </div>
        </div>
                
        <div id="dialog-checkAccessKey" class="dialog-checkAccessKey" style="overflow:hidden;" title="Clé d'accès">
            <form method="post" action="#">
                <div class="row">
                    <label>Veuillez saisir la clé d'accès </label>
                    <input type="password" name="password" class="password"/>
                    <button type="submit" style="margin-top: 5px" class="btn btn-success submitPassword">Valider</button>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

src/Arto/GreenBundle/Resources/views/User/edit.html.twig
{% set section = "product" %}

{% extends '::base.html.twig' %}

{% block body %}
    <section class="main white">
        <h2>Modification de mon compte</h2>
        <form method="post" action="{{ path('account_edit') }}" novalidate="novalidate" class="form-horizontal">
            {{ form_widget(form._token) }}
            {{ form_errors(form) }}
            <div class="control-group">
                <label class="control-label">Nom *</label>
                <div class="controls">
                    {{ form_errors(form.lastname) }}
                    {{ form_widget(form.lastname) }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Prénom *</label>
                <div class="controls">
                    {{ form_errors(form.firstname) }}
                    {{ form_widget(form.firstname) }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Adresse *</label>
                <div class="controls">
                    {{ form_errors(form.address) }}
                    {{ form_widget(form.address) }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Ville *</label>
                <div class="controls">
                    {{ form_errors(form.city) }}
                    {{ form_widget(form.city) }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Code postal *</label>
                <div class="controls">
                    {{ form_errors(form.postcode) }}
                    {{ form_widget(form.postcode) }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Société *</label>
                <div class="controls">
                    {{ form_errors(form.company) }}
                    {{ form_widget(form.company) }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Activité *</label>
                <div class="controls">
                    {{ form_errors(form.activity) }}
                    {{ form_widget(form.activity) }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">SIRET *</label>
                <div class="controls">
                    {{ form_errors(form.siret) }}
                    {{ form_widget(form.siret) }}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Téléphone *</label>
                <div class="controls">
                    {{ form_errors(form.tel) }}
                    {{ form_widget(form.tel) }}
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <a href="{{ path('account') }}" class="btn">Annuler</a>
                    <button type="submit" class="btn btn-success">Valider</button>
                </div>
            </div>
        </form>
    </section>
{% endblock %}

src/Arto/GreenBundle/Resources/views/User/license_used.html.twig
{% set section = "home" %}

{% extends '::base.html.twig' %}

{% block body %}

<section class="main white error-page">
    <h2>Licences</h2>
    <h3>Désolé, toutes les licenses pour le logiciel sont utilisées</h3>
    <p>Merci de nous contacter pour commander d'autres licences</p>
    <p style="margin-top: 50px;">
        <a href="{{ path('account') }}" class="btn">Accéder à mon compte</a>
        <a href="{{ path('green') }}" class="btn">Retourner à l'accueil</a>
    </p>
</section>

{% endblock %}

src/Arto/GreenBundle/Resources/views/User/login.html.twig
{% set section = "user" %}

{% extends '::base.html.twig' %}

{% block body %}
    <section class="main white">
        <h2 style="text-align: center;">Authentification</h2>
        <div class="row-fluid">
            <div class="span6 well connect" style="text-align: center;">
                <h3>connexion</h3>
                <form action="{{ path('login_check') }}" method="post">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-envelope"></i></span>
                        <input name="_username" type="text" placeholder="Identifiant">
                    </div>
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-key"></i></span>
                        <input name="_password" type="password" placeholder="Mot de passe">
                    </div>
                    <button type="submit" class="btn" style="margin-left: 156px;">Valider</button>
                </form>
            </div>
            <div class="span6 well register" style="text-align: center;">
                <h3>Pas encore de compte ?</h3>
                <h4 style="margin-bottom: 26px">Créez le gratuitement maintenant</h4>
                <a href="{{ path('register') }}" class="btn btn-large btn-primary" style="margin-bottom: 30px">Créer un compte</a>
            </div>
        </div>
    </section>
{% endblock %}

src/Arto/GreenBundle/Resources/views/User/mail_account.html.twig
{% extends '::email_base.html.twig' %}

{% block body %}
Bonjour<br><br>

Voici vos codes d'accès :<br>
- Identifiant : {{ user.username }}<br>
- Mot de passe : {{ user.password }}<br><br>

Pour un test gratuit des outils webs Artogreen, veuillez écrire un mail de demande à <a href="mailto:artogreensoft@gmail.com">artogreensoft@gmail.com</a> <br/>
Pour un renouvellement de compte ou une création de compte, contacter l'équipe Artogreen pour émission d'un devis à <a href="mailto:artogreensoft@gmail.com">artogreensoft@gmail.com</a> <br/>
Toute autre action restera sans suite.<br/><br/>

Vous remerciant de votre confiance, et restant à votre écoute.<br/><br/>
Le service Client ArtoGreen

{% endblock %}

src/Arto/GreenBundle/Resources/views/User/mail_password.html.twig
{% extends '::email_base.html.twig' %}

{% block body %}
Bonjour<br><br>

Voici vos informations pour vous connecter à votre compte utilisateur :<br>
- Identifiant : {{ user.username }}<br>
- Mot de passe : {{ user.password }}<br><br>

Vous pouvez accéder à toutes les informations concernant votre compte<br/>

Pour toute question supplémentaire, vous pouvez prendre contact avec votre assistance par mail à <a href="mailto:contact@artogreen.com">contact@artogreen.com</a>.<br/>
Vous remerciant de votre confiance, et restant à votre écoute.<br/><br/>
Le service Client ArtoGreen

{% endblock %}

src/Arto/GreenBundle/Resources/views/User/register_confirm.html.twig
{% set section = "product" %}

{% extends '::base.html.twig' %}

{% block body %}
    <section class="main white">
        <h2>Bienvenue {{ user.firstname }} {{ user.lastname }}</h2>
        <p>
            <strong>Votre compte a été créé avec succès !</strong><br/>
            Un email vous a été envoyé à "{{ user.email }}"" avec vos identifiants de connexion.
        </p>
        <p>
            <a href="{{ path('green') }}" class="btn btn-large btn-success" style="width: 300px">Cliquez ici pour vous authentifier</a>
        </p>
    </section>
{% endblock %}